export const BOOK_SEARCH = 'BOOK_SEARCH';
export const BOOK_SEARCH_RECIEVE = 'BOOK_SEARCH_RECIEVE';
export const ERROR_REQUESTS = 'ERROR_REQUESTS';
export const SUCCESS_REQUESTS = 'SUCCESS_REQUESTS';
