export const ALL_PRODUCTS = 'ALL_PRODUCTS';
export const ALL_PRODUCTS_RECIEVE = 'ALL_PRODUCTS_RECIEVE';
export const ERROR_REQUESTS = 'ERROR_REQUESTS';
export const SUCCESS_REQUESTS = 'SUCCESS_REQUESTS';
