export const ADD_TO_CART = 'ADD_TO_CART';
export const INCREASE_CART_ITEM = 'INCREASE_CART_ITEM';
export const DECREASE_CART_ITEM = 'DECREASE_CART_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const TOTAL_PRICE = 'TOTAL_PRICE';
export const SUBMIT_ORDER = 'SUBMIT_ORDER';

